name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Salesforce CLI
        run: |
          echo 'Installing Salesforce CLI...'
          sfdx --version
          sfdx plugins --core
        shell: bash

      - name: Authenticate with Salesforce
        run: sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile ${{ secrets.SF_JWT_KEY_FILE }} --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername
        env:
          SFDX_DISABLE_DDA: true

      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -x manifest/package.xml
