name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Salesforce CLI
        run: |
          echo 'Installing Salesforce CLI...'
          npm install sfdx-cli --global
          sfdx --version
          sfdx plugins --core
        shell: bash

      - name: Authenticate with Salesforce
        run: |
          echo "${{ secrets.SF_JWT_KEY_FILE }}" > jwt.key
          sfdx force:auth:jwt:grant --clientid ${{ secrets.SF_CLIENT_ID }} --jwtkeyfile jwt.key --username ${{ secrets.SF_USERNAME }} --setdefaultdevhubusername
        env:
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SFDX_DISABLE_DDA: true

      - name: Deploy to Salesforce
        run: sfdx force:source:deploy -x manifest/package.xml
